project:
  type: website
  output-dir: _site

website:
  title: "Depth First"
  description: "A record of going extremely deep on many unrelated things"
  site-url: https://adamdadeh.github.io
  navbar: false
  page-footer:
    center: ""
  search: false

execute:
  enabled: false

format:
  html:
    theme: none
    css: styles.css
    page-layout: full
    toc: false
    number-sections: false
    include-in-header: _quarto-head.html
    html-math-method: mathjax
    code-fold: true
    code-tools: true
