---
title: Curious view of Topology as Category Construction
date: '2022-06-04'
categories:
- Math
description: ''
draft: true
---

Reviewing definitions and debate on "mathematical struture" [cite] - the definitions appear to force the algebraic structure and measure, topological structures together as opposed identifying a truly unifying abstraction. Hence, this digression...

Topology as Category
------------

A topology is a set $X$ with a set $\mathcal{O}$ of subsets of $X$ (the open sets) such that $\mathcal{O}$ is

- Closed under finite intersections
- Closed under arbitrary unions
- Contains the empty set, $\emptyset$ and $X$.

For an algebraic structure (Universal Algebra - https://en.wikipedia.org/wiki/Universal_algebra) on a set $X$ the standard constructions involve function on $X$, $f: X \to Y$, marked points $f: 1 \to X$, n-ary operations $b: X \times X \to X$, and more generally functions $g: \prod_{i \in N} X_i \times Y : \to \prod_{j \in M} X_j \times Z$

Note that subsets fall neatly into this family as functions $U : X \to Bool$. With this view the finite intersection of $U_i$, $\cap_i U_i = \land_i U_i$ is the pointwise logical `and`.
Union is the pointwise logical `or`.

Morphisms, continuous functions, $f : X \to Y$ are s.t for all open sets $V$ the pre-image is open in $X$. $V in \in \mathcal{O}_Y$, $f^{-1}(V) \in \mathcal{O}_X$.
As Boolean functions $f^{-1}(V) : X \rightarrow Bool$ is $V \circ f$.

A continuous function $f: X \to Y$ satisfies - for all $V \in \mathcal{O}_Y$, $V \circ f \in \mathcal{O}_X$.

This is reminiscent of the structure of a comman category. Doesn't fit exactly but appears to be a generalization of a comma category.

Starting from the category of sets.

The slice category $(Set \vert X)$ will have as objects $f : Y \rightarrow X$ and arrows $\phi : Y \rightarrow Y'$ such that $f' \cdot \phi = f$

To fit our use case we extend to a broader concept. 

Given a categorcy $C$ (Set), fixed object $X$ ($Bool$ in our case) we define a category 

* Objects : an object $Y$ with a set of morphisms $U \subsetY \to X$.
* Arrows : morphism from $f : Y \to Y'$ such $u = u' \circ f$ for all $u' \in U'$. Or using notation $U' \circ f = \\{ u' \circ f \vert u' \in U'\\}$, $U' \circ f \subset U$

The familiar slice category is a generalized slice category where $U$ is always one element.

We need to additionally place the conditions for intersection and unions on $U$.

A topology is then a generalized slice category w/ Set & Bool. Continuous functions are morphisms.

Is this generalized slice category a familiar construction? [My knowledge of Category theory is limited to working through half of Categories for the Working Mathematician]

Is this view useful? I can imagine modifying the target $Bool$ with $\land$, $\lor$ to 

Topological Group
----

This is a set G which has both a
group structure and a topological structure, in such a way that the group
multiplication and the group inverse are both continuous in the sense of the
given topology.
For example, t

Consider a topology $U_\alpha : X \to Bool$
Binary operation $b: X \times X \to X$ continuous.
so any open set of $X$ (U_\alpha) has preimage that is open in $X \times X$ so is union of $U_\beta \times U_\gamma$

For above we would say that

$U_\alpha \cdot b : X \times X \to Bool$
Is in the span of $U_\beta \times U_\gamma$
which we already consider language like this when our means to access the topology is as generated by a particular set of generators (basis or sub-basis)
